pipeline:
  name: SimpleWeb_Python_CI
  identifier: SimpleWeb_Python_CI
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: simple-web-backend
        build: <+input>
  stages:
    - stage:
        name: Build_and_artifact
        identifier: Build_and_artifact
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: test connection
                  identifier: test_connection
                  spec:
                    shell: Sh
                    command: echo "pipeline started"
              - step:
                  type: Semgrep
                  name: Semgrep
                  identifier: Semgrep
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
                      args:
                        cli: "--config auto --upload --sarif --output=semgrep-output.sarif ."
                    settings:
                      SEMGREP_APP_TOKEN: <+secrets.getValue("project.SEMGREP_APP_TOKEN")>
                    auth:
                      access_token: <+secrets.getValue("project.SEMGREP_APP_TOKEN")>
                  timeout: 10m
              - step:
                  type: Bandit
                  name: Bandit
                  identifier: Bandit
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: Gurpreetdockerhub
                    repo: gurpreetghs/simple_python_be
                    tags:
                      - ${pipeline.sequenceId}
                    caching: true
        delegateSelectors:
          - aws-delegate
  description: This pipeline was updated by Gurpreet.
  variables:
    - name: DATABASE_URL
      type: String
      description: posgresql url
      required: false
      value: <+input>
    - name: JWT_SECRET_KEY
      type: String
      description: ""
      required: false
      value: <+input>
    - name: pin
      type: String
      description: ""
      required: false
      value: <+input>
